import { createFileRoute } from "@tanstack/react-router";
import { BarChart3, CalendarDays, ClipboardCheck, Download, RefreshCw, TrendingUp, Users } from "lucide-react";
import { useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeading } from "@/components/page-heading";
import { Button } from "@/components/ui/button";
import { useWaswia } from "@/lib/waswia-store";

export const Route = createFileRoute("/admin/reporting")({ head: () => ({ meta: [{ title: "Reporting — WASWIA" }, { name: "description", content: "Analyse et statistiques des données collectées avec WASWIA." }, { property: "og:title", content: "Reporting — WASWIA" }, { property: "og:description", content: "Analyse et statistiques des données collectées avec WASWIA." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Reporting });

const chartData = [{ day: "11 août", value: 0 }, { day: "16 août", value: 1 }, { day: "21 août", value: 0 }, { day: "26 août", value: 3 }, { day: "31 août", value: 2 }, { day: "5 sept.", value: 4 }, { day: "10 sept.", value: 0 }];

function Reporting() {
  const { surveys, investigators } = useWaswia(); const [tab, setTab] = useState("Tendances"); const [updated, setUpdated] = useState(false);
  const stats = [{ label: "Réponses totales", value: "0", detail: "0 terminées", icon: ClipboardCheck, tone: "bg-primary/10 text-primary" }, { label: "Taux d'achèvement", value: "0%", detail: "des sondages terminés", icon: TrendingUp, tone: "bg-success-soft text-success" }, { label: "Enquêteurs actifs", value: "0", detail: "sur la période", icon: Users, tone: "bg-cyan-soft text-cyan" }, { label: "Durée moyenne", value: "0 min", detail: "par sondage", icon: CalendarDays, tone: "bg-warning-soft text-warning" }];
  return <div className="space-y-6"><PageHeading title="Reporting" subtitle="Analyse et statistiques des données collectées" actions={<div className="hidden gap-2 sm:flex"><Button variant="outline" onClick={() => { setUpdated(true); window.setTimeout(() => setUpdated(false), 700); }}><RefreshCw className={updated ? "animate-spin" : ""} /> Actualiser</Button><Button variant="outline"><Download /> CSV</Button><Button variant="outline"><BarChart3 /> Excel</Button></div>} /><section className="rounded-xl bg-card p-6 shadow-md"><h2 className="font-bold">Filtres</h2><div className="mt-4 grid gap-4 lg:grid-cols-[280px_200px_200px]"><div className="flex h-10 items-center gap-3 rounded-lg border border-input px-4 text-sm"><CalendarDays className="h-4 w-4" />11 août - 10 sept. 2026</div><select className="h-10 rounded-lg border border-input bg-background px-3 text-sm"><option>Tous les sondages</option>{surveys.map((s) => <option key={s.id}>{s.title}</option>)}</select><select className="h-10 rounded-lg border border-input bg-background px-3 text-sm"><option>Tous les enquêteurs</option>{investigators.map((p) => <option key={p.id}>{p.name}</option>)}</select></div></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => <article key={stat.label} className="grid grid-cols-[minmax(0,1fr)_auto] items-center rounded-xl bg-card p-6 shadow-md"><div><p className="text-sm text-muted-foreground">{stat.label}</p><p className="mt-1 text-3xl font-bold">{stat.value}</p><p className="mt-2 text-xs text-muted-foreground">{stat.detail}</p></div><span className={`grid h-12 w-12 place-items-center rounded-xl ${stat.tone}`}><stat.icon /></span></article>)}</section><div className="inline-flex rounded-lg bg-muted p-1">{["Tendances", "Par sondage", "Par enquêteur"].map((item) => <Button key={item} variant="ghost" size="sm" onClick={() => setTab(item)} className={tab === item ? "bg-card shadow-sm" : "text-muted-foreground"}>{item}</Button>)}</div><section className="rounded-xl bg-card p-6 shadow-md"><h2 className="text-2xl font-bold">{tab === "Tendances" ? "Évolution des réponses" : tab}</h2><p className="mt-1 text-sm text-muted-foreground">Nombre de réponses collectées par jour</p><div className="mt-6 h-[320px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="waswiaChart" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="var(--primary)" stopOpacity={0.25}/><stop offset="95%" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="var(--border)" /><XAxis dataKey="day" tickLine={false} axisLine={false} /><YAxis tickLine={false} axisLine={false} /><Tooltip /><Area type="monotone" dataKey="value" stroke="var(--primary)" strokeWidth={3} fill="url(#waswiaChart)" /></AreaChart></ResponsiveContainer></div></section></div>;
}