import { createFileRoute } from "@tanstack/react-router";
import { ClipboardList, Eye, Mail, MoreVertical, Pencil, Plus, Search, Trash2, UserPlus } from "lucide-react";
import { useState, type FormEvent } from "react";
import { PageHeading } from "@/components/page-heading";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { useWaswia } from "@/lib/waswia-store";

export const Route = createFileRoute("/admin/investigators")({ head: () => ({ meta: [{ title: "Enquêteurs — WASWIA" }, { name: "description", content: "Gérez l'équipe terrain WASWIA." }, { property: "og:title", content: "Enquêteurs — WASWIA" }, { property: "og:description", content: "Gérez l'équipe terrain WASWIA." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Investigators });

function Investigators() {
  const { investigators, addInvestigator, deleteInvestigator } = useWaswia(); const [query, setQuery] = useState(""); const [open, setOpen] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); addInvestigator({ name: String(data.get("name")), email: String(data.get("email")) }); setOpen(false); };
  const filtered = investigators.filter((p) => `${p.name} ${p.email}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="space-y-7"><PageHeading title="Enquêteurs" subtitle="Gérez votre équipe terrain" actions={<Button className="bg-brand-gradient" onClick={() => setOpen(true)}><UserPlus /> Ajouter un enquêteur</Button>} /><div className="relative max-w-md"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Rechercher un enquêteur..." className="h-10 pl-10" /></div><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((person) => <article key={person.id} className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-start gap-4 rounded-xl bg-card p-4 shadow-md"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-brand-gradient text-lg font-bold text-primary-foreground">{person.name.charAt(0)}</div><div className="min-w-0"><h2 className="font-bold">{person.name}</h2><p className="flex items-center gap-1 truncate text-sm text-muted-foreground"><Mail className="h-3 w-3 shrink-0" />{person.email}</p><span className="mt-2 inline-flex items-center gap-1 rounded-full bg-cyan px-3 py-1 text-xs font-bold text-primary-foreground"><ClipboardList className="h-3 w-3" /> {person.surveys} sondages</span></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label={`Actions pour ${person.name}`}><MoreVertical /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem><Eye /> Voir les assignations</DropdownMenuItem><DropdownMenuItem onSelect={() => setOpen(true)}><Pencil /> Modifier</DropdownMenuItem><DropdownMenuItem><ClipboardList /> Assigner un sondage</DropdownMenuItem><DropdownMenuItem onSelect={() => deleteInvestigator(person.id)} className="text-destructive"><Trash2 /> Supprimer</DropdownMenuItem></DropdownMenuContent></DropdownMenu></article>)}</section><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Ajouter un enquêteur</DialogTitle><DialogDescription>Créez un nouveau membre de l'équipe terrain.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium">Nom complet<Input name="name" required className="mt-2" /></label><label className="block text-sm font-medium">Email<Input name="email" type="email" required className="mt-2" /></label><Button type="submit" className="w-full bg-brand-gradient"><Plus /> Ajouter</Button></form></DialogContent></Dialog></div>;
}