/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminInvestigatorsRouteImport } from './routes/admin.investigators'
import { Route as AdminReportingRouteImport } from './routes/admin.reporting'
import { Route as AdminResponsesRouteImport } from './routes/admin.responses'
import { Route as AdminSurveysRouteImport } from './routes/admin.surveys'
import { Route as AdminSurveysSurveyIdRouteImport } from './routes/admin.surveys.$surveyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvestigatorsRoute = AdminInvestigatorsRouteImport.update({
  id: '/investigators',
  path: '/investigators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportingRoute = AdminReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResponsesRoute = AdminResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveysRoute = AdminSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveysSurveyIdRoute = AdminSurveysSurveyIdRouteImport.update({
  id: '/$surveyId',
  path: '/$surveyId',
  getParentRoute: () => AdminSurveysRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/investigators': typeof AdminInvestigatorsRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin/surveys': typeof AdminSurveysRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/investigators': typeof AdminInvestigatorsRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin/surveys': typeof AdminSurveysRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/investigators': typeof AdminInvestigatorsRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin/surveys': typeof AdminSurveysRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/investigators'
    | '/admin/reporting'
    | '/admin/responses'
    | '/admin/surveys'
    | '/admin/'
    | '/admin/surveys/$surveyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/investigators'
    | '/admin/reporting'
    | '/admin/responses'
    | '/admin/surveys'
    | '/admin'
    | '/admin/surveys/$surveyId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/investigators'
    | '/admin/reporting'
    | '/admin/responses'
    | '/admin/surveys'
    | '/admin/'
    | '/admin/surveys/$surveyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/investigators': {
      id: '/admin/investigators'
      path: '/investigators'
      fullPath: '/admin/investigators'
      preLoaderRoute: typeof AdminInvestigatorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reporting': {
      id: '/admin/reporting'
      path: '/reporting'
      fullPath: '/admin/reporting'
      preLoaderRoute: typeof AdminReportingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/responses': {
      id: '/admin/responses'
      path: '/responses'
      fullPath: '/admin/responses'
      preLoaderRoute: typeof AdminResponsesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys': {
      id: '/admin/surveys'
      path: '/surveys'
      fullPath: '/admin/surveys'
      preLoaderRoute: typeof AdminSurveysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys/$surveyId': {
      id: '/admin/surveys/$surveyId'
      path: '/$surveyId'
      fullPath: '/admin/surveys/$surveyId'
      preLoaderRoute: typeof AdminSurveysSurveyIdRouteImport
      parentRoute: typeof AdminSurveysRoute
    }
  }
}

interface AdminSurveysRouteChildren {
  AdminSurveysSurveyIdRoute: typeof AdminSurveysSurveyIdRoute
}

const AdminSurveysRouteChildren: AdminSurveysRouteChildren = {
  AdminSurveysSurveyIdRoute: AdminSurveysSurveyIdRoute,
}

const AdminSurveysRouteWithChildren = AdminSurveysRoute._addFileChildren(
  AdminSurveysRouteChildren,
)

interface AdminRouteChildren {
  AdminInvestigatorsRoute: typeof AdminInvestigatorsRoute
  AdminReportingRoute: typeof AdminReportingRoute
  AdminResponsesRoute: typeof AdminResponsesRoute
  AdminSurveysRoute: typeof AdminSurveysRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInvestigatorsRoute: AdminInvestigatorsRoute,
  AdminReportingRoute: AdminReportingRoute,
  AdminResponsesRoute: AdminResponsesRoute,
  AdminSurveysRoute: AdminSurveysRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
